services:
  laravel:
    build:
      context: 'laravel'
      dockerfile: 'Dockerfile'
      args:
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'LARAVEL_VERSION=${LARAVEL_VERSION}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'XDEBUG=${XDEBUG}'
        - 'INSTALL_ADDITIONAL_EXTENSIONS=${INSTALL_ADDITIONAL_EXTENSIONS}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_LARAVEL}:cached'
    ports:
      - '${LARAVEL_HOST_HTTP_PORT}:80'
volumes: {}
