services:
  laravel:
    build:
      context: 'laravel'
      dockerfile: 'Dockerfile'
      args:
        PHP_VERSION: ${PHP_VERSION}
        LARAVEL_VERSION: ${LARAVEL_VERSION}
        DISPLAY_PHPERROR: ${DISPLAY_PHPERROR}
        XDEBUG: ${XDEBUG}
        INSTALL_ADDITIONAL_EXTENSIONS: ${INSTALL_ADDITIONAL_EXTENSIONS}
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - '${APP_CODE_PATH_HOST}:/var/www/html:cached'
    ports:
      - '${LARAVEL_HOST_HTTP_PORT}:80'
