#User defined
user:
  php_version:
    label:
      PHP version
    hint:
      Select a PHP version from the list above
    type:
      select
    values:
      - "8.2"
      - "8.3"
      - "8.4"
    target:
      PHP_VERSION
  
  backend_ws:
      label:
        Laravel version
      hint:
        Select a laravel version
      type:
        select
      values:
        - "10"
        - "11"
        - "12"
      target:
        LARAVEL_VERSION
  
  additional_extensions:
      label:
        PHP Extensions
      hint:
        Select your php extensions
      type:
        multiple-select
      values:
        - "pdo_mysql"
      target:
        INSTALL_ADDITIONAL_EXTENSIONS

  php_error_reporting:
    label:
      Enable PHP error reporting?
    type:
      checkbox
    hint: Check the box to display PHP errors 
    target:
      DISPLAY_PHPERROR

  php_xdebug:
    label:
      Enable PHP extension XDEBUG?
    type:
      checkbox
    hint: Check the box to display extension xdebug
    target:
      XDEBUG

#System defaults
system:
  show_localpath_selector:
    true
  #Generate public ports for the docker image
  ports:
    http:
      LARAVEL_HOST_HTTP_PORT
